/**
 * One module's complete build brief, derived from docs/BUILD-ORDER.md.
 *
 * Same argument as `cid:pack`, one stage further down. A builder that reads the whole
 * build order to find its own section, then opens three sibling modules to learn what it
 * may call, is paying to re-derive something a parser states once.
 *
 * But the reason this file exists is not cost. It is that **the build order is the first
 * artifact in this repo addressed to a reader who does not exist**, and until something
 * consumes it, nobody knows whether 37 spec sheets actually answer a builder's questions.
 * This makes that answerable.
 *
 * The measurement it enables matters more than the code it produces. `BUILD-ORDER.md`
 * rule 1 says: do not invent a value, stop and report it. So:
 *
 *   stops                 gaps the spec was honest about. Cheap to fix.
 *   silent divergences    the builder decided something, did not think to ask, and landed
 *                         somewhere other than the hand-written control. Ambiguity the
 *                         spec did not know it had. These are the dangerous ones.
 *
 * For that to mean anything the builder must not see the answer. The control
 * (`game/src/server/init.server.luau`) was hand-written by the same person who directed
 * the agents that wrote the specs, so a match after reading it proves nothing at all.
 */

import { readFile } from 'node:fs/promises';

const ORDER = 'docs/BUILD-ORDER.md';

/** Everything under `## N. \`name\` — side`, up to the next module heading. */
function sectionFor(body, name) {
  const re = new RegExp(`^## \\d+\\. \`${name}\` — .*$`, 'm');
  const m = body.match(re);
  if (!m) return null;
  const from = m.index;
  const rest = body.slice(from + m[0].length);
  const next = rest.search(/^## \d+\. `/m);
  return m[0] + (next < 0 ? rest : rest.slice(0, next));
}

function field(section, label) {
  const m = section.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`));
  return m ? m[1].trim() : null;
}

/** The bulleted list under a `### Heading`. */
function bullets(section, heading) {
  const i = section.indexOf(`### ${heading}`);
  if (i < 0) return [];
  const rest = section.slice(i + heading.length + 4);
  const end = rest.search(/\n###\s/);
  return [...(end < 0 ? rest : rest.slice(0, end)).matchAll(/^-\s+(.+)$/gm)].map((b) => b[1].trim());
}

function dependencies(section) {
  const raw = field(section, 'Depends on') ?? '';
  if (/^nothing/i.test(raw)) return [];
  return [...raw.matchAll(/`([^`]+)`/g)].map((m) => m[1]);
}

export function listModules(body) {
  return [...body.matchAll(/^## (\d+)\. `([^`]+)` — (\S+)$/gm)]
    .map((m) => ({ n: Number(m[1]), name: m[2], side: m[3] }));
}

/**
 * @param {string} body docs/BUILD-ORDER.md
 * @param {string} name module to brief
 */
export function buildPack(body, name) {
  const section = sectionFor(body, name);
  if (!section) {
    const known = listModules(body).map((m) => m.name).join(', ');
    throw new Error(`no module "${name}" in ${ORDER}. Known: ${known}`);
  }

  const deps = dependencies(section);
  const target = (field(section, 'Write to') ?? '').replace(/`/g, '');

  // What a dependency offers, without opening its source. If it has not been written yet
  // the builder is told so plainly rather than left to discover an empty file.
  const depBriefs = deps.map((d) => {
    const s = sectionFor(body, d);
    return {
      name: d,
      exposes: s ? bullets(s, 'Must expose') : [],
      path: s ? (field(s, 'Write to') ?? '').replace(/`/g, '') : null,
      owns: s ? field(s, 'Owns') : null,
    };
  });

  return { section, deps: depBriefs, target, name };
}

export function renderBuildPack({ section, deps, target, name }) {
  return `# Build brief — \`${name}\`

**Generated by \`npm run build:pack\`. This is everything. Do not go looking for more.**

You are writing **one module**. The specification below was produced by a design pipeline
whose entire purpose was to make sure you never have to guess. If it worked, you will not
need anything that is not on this page.

---

## The two rules, and why they are the point

**1. Do not invent a value.** If you need a number, a name, a rate or a threshold that is
not listed under *Values* below, **stop and write it down** rather than choosing one. A
chosen number is indistinguishable from a specified one once it is in the code, which is
exactly how a design pipeline silently stops mattering.

**2. The prohibitions are not advice.** A *Must not* entry is there because the design
breaks without it, usually for a reason recorded in a spec sheet you cannot see.

**You are being measured on rule 1, not on finishing.** A module with four honest stops is
a better result than a module with none and four quiet guesses. Report every one.

---

## What you may read

| | |
|---|---|
| this brief | yes, it is the whole specification |
| \`game/src/shared/GameConfig.luau\` | **yes.** It is generated from the same values below, and it shows the module conventions this repo uses. |
| your dependencies' source, listed below | yes, to check a signature |
| \`game/src/server/init.server.luau\` | **no. Never open this file.** |
| \`game/src/client/init.client.luau\` | **no. Never open this file.** |
| \`cid/\`, the spec sheets | no. If the answer is only in there, the build order has a gap and that is the finding. |

Those two forbidden files are a working implementation of this game, written by hand by
the same person who directed the agents that wrote the specs. Reading them would tell you
the answer and destroy the only measurement this exercise produces. **If you find yourself
opening them to resolve an ambiguity, that ambiguity is a stop. Write it down instead.**

---

## Your module

${section.trim()}

---

## What your dependencies give you

${deps.length
      ? deps.map((d) => `### \`${d.name}\`${d.path ? ` — \`${d.path}\`` : ''}

${d.owns ? `${d.owns}\n` : ''}
${d.exposes.length ? d.exposes.map((e) => `- ${e}`).join('\n') : '_(exposes nothing declared)_'}`).join('\n\n')
      : '_Nothing. This module is a leaf._'}

**Call these, do not reimplement them.** If a dependency does not expose what you need,
that is a gap in the build order: stop and report it.

---

## What to write

**The module:** \`${target}\`

Luau, \`--!strict\`, returning a table. Match the conventions in \`GameConfig.luau\`.

**The report:** \`${target.replace(/\.luau$/, '')}.report.md\`

This is the artifact the exercise exists to produce. Write it even if it is empty:

\`\`\`markdown
# Build report — ${name}

## Stops
<Every value, name, rate or behaviour you needed and could not find. One per line, each
naming what you needed and what you would have had to invent. "None" if none.>

## Decided without a stated value
<Every call you made that the brief did not settle but that you judged too small to stop
for: a variable name, a loop shape, an error message, an ordering. Be honest and generous
here. This is the list that shows where the specification is thinner than it looks.>

## Assumed about a dependency
<Anything you assumed about a module you did not write.>
\`\`\`

The second section is the one that matters most and the one you will be tempted to leave
short. A stop is a gap the specification knew about. Something you decided quietly is a gap
it did not, and those are the ones that make two builders produce two different games.
`;
}
