/**
 * Spec + theme -> Luau.
 *
 * Emits three things:
 *   Theme.luau      the token table, generated from the same theme the preview used
 *   Screens/*.luau  each spec as a plain data table
 *   UIBuilder.luau  the runtime that turns those tables into Instances
 *
 * Specs stay DATA on the Roblox side too. That keeps the shipped artifact
 * isomorphic to what the validator measured — if the emitter flattened specs
 * into imperative Instance.new calls, the two representations could drift and
 * nothing would notice.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/* ------------------------------------------------------- lua serialisation */

const LUA_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;

const luaKey = (k) => (LUA_IDENT.test(k) ? k : `["${k}"]`);

function luaValue(v, indent = 0) {
  const pad = '\t'.repeat(indent);
  const padIn = '\t'.repeat(indent + 1);

  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isInteger(v) ? String(v) : String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;

  if (Array.isArray(v)) {
    // Nils inside an array break Lua's length operator, so they are coerced to
    // 0 — which matches how the transpiler reads a missing scale/offset anyway.
    const items = v.map((x) => luaValue(x === null || x === undefined ? 0 : x, indent + 1));
    return `{ ${items.join(', ')} }`;
  }

  const entries = Object.entries(v).filter(([, val]) => val !== null && val !== undefined);
  if (!entries.length) return '{}';
  const body = entries
    .map(([k, val]) => `${padIn}${luaKey(k)} = ${luaValue(val, indent + 1)},`)
    .join('\n');
  return `{\n${body}\n${pad}}`;
}

/* ------------------------------------------------------------ normalisation */

/** UDim2 argument order: scaleX, offsetX, scaleY, offsetY. */
function udim2(part) {
  if (!part) return null;
  return [part.s?.[0] ?? 0, part.o?.[0] ?? 0, part.s?.[1] ?? 0, part.o?.[1] ?? 0];
}

const PASSTHROUGH = [
  'class', 'name', 'bg', 'bgTransparency', 'corner', 'stroke', 'gradient', 'padding',
  'layout', 'flex', 'aspect', 'clip', 'scroll', 'zIndex', 'elevation', 'rotation',
  'text', 'type', 'color', 'align', 'alignY', 'wrap', 'textTransparency', 'textStroke',
  'image', 'imageFit', 'imageTint', 'slice', 'placeholder', 'preview', 'states', 'motion',
  'state', 'aspectMode',
];

/** Convert one spec node into the flat table shape the Luau runtime consumes. */
function normalize(node) {
  const out = {};
  for (const key of PASSTHROUGH) {
    if (node[key] !== undefined) out[key] = node[key];
  }

  if (node.size) {
    out.size = udim2(node.size);
    if (node.size.auto) out.auto = node.size.auto;
  }
  if (node.pos) out.pos = udim2(node.pos);
  if (node.maxSize) out.maxSize = udim2(node.maxSize);
  if (node.anchor) out.anchor = node.anchor;

  // Placeholder art that never got generated stays a marker rather than
  // becoming a broken rbxassetid.
  if (node.image && typeof node.image === 'object') {
    out.image = null;
    out.placeholder = node.image.placeholder;
  }

  if (node.at) {
    out.at = Object.fromEntries(Object.entries(node.at).map(([vp, override]) => [vp, normalize(override)]));
  }
  if (node.children?.length) out.children = node.children.map(normalize);
  return out;
}

/* --------------------------------------------------------------- emitters */

function emitTheme(theme) {
  return `--!strict
-- GENERATED by ui-forge. Do not edit by hand.
-- Archetype: ${theme.meta.archetype} (${theme.meta.archetypeLabel})
--
-- Colours are stored as hex strings and converted by UIBuilder, so this table
-- stays diffable and matches the JSON the preview validated against byte for byte.

return ${luaValue(theme, 0)}
`;
}

function emitScreen(spec, name) {
  return `--!strict
-- GENERATED by ui-forge. Do not edit by hand.
-- Screen: ${spec.screen ?? name}${spec.provenance ? `\n-- Pattern: ${spec.provenance.pattern}` : ''}
--
-- This is DATA, not code. UIBuilder.build() turns it into Instances.

return ${luaValue({ name: spec.name ?? name, focus: spec.focus, root: normalize(spec.root) }, 0)}
`;
}

/**
 * @param {object} opts { spec, theme, outDir, name, assetIndex }
 */
export async function emitLuau({ spec, theme, outDir, name, assetIndex }) {
  // Substitute real asset ids where we have them; anything unresolved stays a
  // placeholder marker the runtime renders as a visible magenta box.
  const withAssets = JSON.parse(JSON.stringify(spec));
  if (assetIndex) {
    const walk = (n) => {
      const ph = n.image && typeof n.image === 'object' ? n.image.placeholder : null;
      if (ph && assetIndex[ph]?.assetId) n.image = assetIndex[ph].assetId;
      for (const c of n.children ?? []) walk(c);
    };
    walk(withAssets.root);
  }

  await mkdir(resolve(outDir, 'Screens'), { recursive: true });

  const runtime = await readFile(resolve(__dirname, 'runtime', 'UIBuilder.luau'), 'utf8');
  const files = {
    'UIBuilder.luau': runtime,
    'Theme.luau': emitTheme(theme),
    [`Screens/${name}.luau`]: emitScreen(withAssets, name),
  };

  for (const [rel, contents] of Object.entries(files)) {
    await writeFile(resolve(outDir, rel), contents, 'utf8');
  }
  return Object.keys(files).map((f) => resolve(outDir, f));
}
